name: imaging-study-analysis
channels:
  - defaults
dependencies:
  - python=3.6
  - matplotlib
  - pandas
  - numpy
  - statsmodels
  - ipython
  - xlrd
  - xlwt
  - pydicom
  - pip:
    - grabbit
    - dicom2nifti
    - SimpleITK